export const ADD_CALL = 'ADD_CALL';
export const ADD_ELEVATOR_STATE = 'ADD_ELEVATOR_STATE';
export const SET_ELEVATOR_STATE = 'SET_ELEVATOR_STATE';
export const SET_ELEVATOR_DURATION = 'SET_ELEVATOR_DURATION';
export const ADD_BUTTON_STATE = 'ADD_BUTTON_STATE';
export const SET_BUTTON_STATE = 'SET_BUTTON_STATE';
